/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VnVaultRouteImport } from './routes/vn-vault'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as OnDeckRouteImport } from './routes/on-deck'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as KpiRouteImport } from './routes/kpi'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GhlClaimsRouteImport } from './routes/ghl-claims'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProspectsIndexRouteImport } from './routes/prospects.index'
import { Route as ProspectsIdRouteImport } from './routes/prospects.$id'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'

const VnVaultRoute = VnVaultRouteImport.update({
  id: '/vn-vault',
  path: '/vn-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const OnDeckRoute = OnDeckRouteImport.update({
  id: '/on-deck',
  path: '/on-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiRoute = KpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GhlClaimsRoute = GhlClaimsRouteImport.update({
  id: '/ghl-claims',
  path: '/ghl-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIndexRoute = ProspectsIndexRouteImport.update({
  id: '/prospects/',
  path: '/prospects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIdRoute = ProspectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProspectsRoute,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/ghl-claims': typeof GhlClaimsRoute
  '/inbox': typeof InboxRoute
  '/keywords': typeof KeywordsRoute
  '/kpi': typeof KpiRoute
  '/linkedin': typeof LinkedinRoute
  '/on-deck': typeof OnDeckRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/playbook': typeof PlaybookRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/training': typeof TrainingRoute
  '/vn-vault': typeof VnVaultRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/prospects/': typeof ProspectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/ghl-claims': typeof GhlClaimsRoute
  '/inbox': typeof InboxRoute
  '/keywords': typeof KeywordsRoute
  '/kpi': typeof KpiRoute
  '/linkedin': typeof LinkedinRoute
  '/on-deck': typeof OnDeckRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/playbook': typeof PlaybookRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/training': typeof TrainingRoute
  '/vn-vault': typeof VnVaultRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/prospects': typeof ProspectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/ghl-claims': typeof GhlClaimsRoute
  '/inbox': typeof InboxRoute
  '/keywords': typeof KeywordsRoute
  '/kpi': typeof KpiRoute
  '/linkedin': typeof LinkedinRoute
  '/on-deck': typeof OnDeckRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/playbook': typeof PlaybookRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/training': typeof TrainingRoute
  '/vn-vault': typeof VnVaultRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/prospects/$id': typeof ProspectsIdRoute
  '/prospects/': typeof ProspectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/ghl-claims'
    | '/inbox'
    | '/keywords'
    | '/kpi'
    | '/linkedin'
    | '/on-deck'
    | '/outreach'
    | '/pipeline'
    | '/playbook'
    | '/settings'
    | '/tools'
    | '/training'
    | '/vn-vault'
    | '/api/transcribe'
    | '/prospects/$id'
    | '/prospects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/ghl-claims'
    | '/inbox'
    | '/keywords'
    | '/kpi'
    | '/linkedin'
    | '/on-deck'
    | '/outreach'
    | '/pipeline'
    | '/playbook'
    | '/settings'
    | '/tools'
    | '/training'
    | '/vn-vault'
    | '/api/transcribe'
    | '/prospects/$id'
    | '/prospects'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/ghl-claims'
    | '/inbox'
    | '/keywords'
    | '/kpi'
    | '/linkedin'
    | '/on-deck'
    | '/outreach'
    | '/pipeline'
    | '/playbook'
    | '/settings'
    | '/tools'
    | '/training'
    | '/vn-vault'
    | '/api/transcribe'
    | '/prospects/$id'
    | '/prospects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  GhlClaimsRoute: typeof GhlClaimsRoute
  InboxRoute: typeof InboxRoute
  KeywordsRoute: typeof KeywordsRoute
  KpiRoute: typeof KpiRoute
  LinkedinRoute: typeof LinkedinRoute
  OnDeckRoute: typeof OnDeckRoute
  OutreachRoute: typeof OutreachRoute
  PipelineRoute: typeof PipelineRoute
  PlaybookRoute: typeof PlaybookRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  TrainingRoute: typeof TrainingRoute
  VnVaultRoute: typeof VnVaultRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ProspectsIndexRoute: typeof ProspectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vn-vault': {
      id: '/vn-vault'
      path: '/vn-vault'
      fullPath: '/vn-vault'
      preLoaderRoute: typeof VnVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-deck': {
      id: '/on-deck'
      path: '/on-deck'
      fullPath: '/on-deck'
      preLoaderRoute: typeof OnDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi': {
      id: '/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof KpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghl-claims': {
      id: '/ghl-claims'
      path: '/ghl-claims'
      fullPath: '/ghl-claims'
      preLoaderRoute: typeof GhlClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/': {
      id: '/prospects/'
      path: '/prospects'
      fullPath: '/prospects/'
      preLoaderRoute: typeof ProspectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/$id': {
      id: '/prospects/$id'
      path: '/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof ProspectsIdRouteImport
      parentRoute: typeof ProspectsRoute
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  GhlClaimsRoute: GhlClaimsRoute,
  InboxRoute: InboxRoute,
  KeywordsRoute: KeywordsRoute,
  KpiRoute: KpiRoute,
  LinkedinRoute: LinkedinRoute,
  OnDeckRoute: OnDeckRoute,
  OutreachRoute: OutreachRoute,
  PipelineRoute: PipelineRoute,
  PlaybookRoute: PlaybookRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  TrainingRoute: TrainingRoute,
  VnVaultRoute: VnVaultRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ProspectsIndexRoute: ProspectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
