/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as KpiRouteImport } from './routes/kpi'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProspectsIdRouteImport } from './routes/prospects.$id'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiRoute = KpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIdRoute = ProspectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProspectsRoute,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/kpi': typeof KpiRoute
  '/linkedin': typeof LinkedinRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/training': typeof TrainingRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/prospects/$id': typeof ProspectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/kpi': typeof KpiRoute
  '/linkedin': typeof LinkedinRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/training': typeof TrainingRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/prospects/$id': typeof ProspectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/kpi': typeof KpiRoute
  '/linkedin': typeof LinkedinRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/training': typeof TrainingRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/prospects/$id': typeof ProspectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/kpi'
    | '/linkedin'
    | '/outreach'
    | '/pipeline'
    | '/prospects'
    | '/settings'
    | '/tools'
    | '/training'
    | '/api/transcribe'
    | '/prospects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations'
    | '/kpi'
    | '/linkedin'
    | '/outreach'
    | '/pipeline'
    | '/prospects'
    | '/settings'
    | '/tools'
    | '/training'
    | '/api/transcribe'
    | '/prospects/$id'
  id:
    | '__root__'
    | '/'
    | '/conversations'
    | '/kpi'
    | '/linkedin'
    | '/outreach'
    | '/pipeline'
    | '/prospects'
    | '/settings'
    | '/tools'
    | '/training'
    | '/api/transcribe'
    | '/prospects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationsRoute: typeof ConversationsRoute
  KpiRoute: typeof KpiRoute
  LinkedinRoute: typeof LinkedinRoute
  OutreachRoute: typeof OutreachRoute
  PipelineRoute: typeof PipelineRoute
  ProspectsRoute: typeof ProspectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  TrainingRoute: typeof TrainingRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi': {
      id: '/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof KpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/$id': {
      id: '/prospects/$id'
      path: '/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof ProspectsIdRouteImport
      parentRoute: typeof ProspectsRoute
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProspectsRouteChildren {
  ProspectsIdRoute: typeof ProspectsIdRoute
}

const ProspectsRouteChildren: ProspectsRouteChildren = {
  ProspectsIdRoute: ProspectsIdRoute,
}

const ProspectsRouteWithChildren = ProspectsRoute._addFileChildren(
  ProspectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationsRoute: ConversationsRoute,
  KpiRoute: KpiRoute,
  LinkedinRoute: LinkedinRoute,
  OutreachRoute: OutreachRoute,
  PipelineRoute: PipelineRoute,
  ProspectsRoute: ProspectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  TrainingRoute: TrainingRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
